name: Delete tag and release
description: delete tag and release
author: "dev-drprasad"

branding:
  color: "red"
  icon: "delete"

inputs:
  branch_name:
    description: branch name
    required: true
  delete_release:
    description: whether to delete release or not
    required: false
    default: true
  repo:
    description: target repository as <owner>/<repository>
    required: false

runs:
  using: "composite"
  steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: cleanup
      shell: bash
      run: |
        sh ./deleteTagsByBranchName.sh