name: Delete tag and release
description: delete tag and release
author: "dev-drprasad"

branding:
  color: "red"
  icon: "delete"

inputs:
  branch_name:
    description: branch name
    required: true
  delete_release:
    description: whether to delete release or not
    required: false
    default: true
  repo:
    description: target repository as <owner>/<repository>
    required: false

runs:
  using: "composite"
  steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: cleanup
      shell: bash
      run: |
        git_branch=${INPUT_BRANCH_NAME:-$GITHUB_REF_NAME}
        tag_format=${git_branch//[^a-zA-Z0-9]/-}
        echo $tag_format
        git fetch --all --tags
        #search patten vX.X.X-branchName-x
        declare -a tags=( $( git tag --list "v[0-9].[0-9].[0-9]-${tag_format}.[0-9]*") )
        for tag_name in "${tags[@]}"
        do
          node index.js ${tag_name}
          echo "git push --delete origin ${tag_name}"
          git push --delete origin ${tag_name}
        done